# Generated by Django 4.1.3 on 2022-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIChapter2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='EmailId',
            field=models.EmailField(max_length=254),
        ),
    ]
